### ISSUE TITLE
bundle takes forever

### ISSUE THREAD

**Issue by svenapel** [ESEC-FSE/ESEC-FSE.github.io#7]
The command for local testing (bundle exec jekyll serve) takes forever in my local installation. Furthermore, there is a couple of warnings when following the instructions in README, which might be related. Please check whether we need to update the instructions.

**Comment by GSeibt** [comment]
I have updated the README in response to the deprecation warnings. On Linux I can't reproduce the bundle call taking forever (same exact version of ruby and bundler). Possibly an issue with WSL. I can see wether it works on my Windows install.

**Comment by GSeibt** [comment]
Not sure if this is an issue anymore. Hasn't happened to me yet. I have however experienced network connections hanging due to TCP packet fragmentation being broken in WSL. I suspect that was the issue.
